import type { Metadata } from 'next';
import { Roboto, Montserrat, Tilt_Warp } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
	subsets: ['latin'],
	variable: '--body-font',
	weight: ['400', '500', '700'],
});
const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--logo-font',
	weight: ['400', '500', '700'],
});
const tiltWarp = Tilt_Warp({
	subsets: ['latin'],
	variable: '--nav-font',
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${roboto.variable} ${montserrat.variable} ${tiltWarp.variable} font-body padding`}>
			<body>{children}</body>
		</html>
	);
}
