import type { Metadata } from 'next';
import { Roboto, Montserrat, Tilt_Warp } from 'next/font/google';
import './globals.css';

import { Providers } from './providers';

import { Footer } from '@/common/components/Footer/Footer';
import { HomeLogo } from '@/common/components/Logo/Logo';
import { MobileNavigation } from '@/common/components/MobileNavigation/MobileNavigation';

const roboto = Roboto({
	subsets: ['latin'],
	variable: '--body-font',
	weight: ['400', '500', '700'],
});
const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--logo-font',
	weight: ['400', '500', '700'],
});
const tiltWarp = Tilt_Warp({
	subsets: ['latin'],
	variable: '--nav-font',
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${roboto.variable} ${montserrat.variable} ${tiltWarp.variable} font-body padding`}
			suppressHydrationWarning={true}>
			<body className="bg-white dark:bg-appBlack transition-bg duration-500">
				<Footer />
				<HomeLogo />
				<Providers> {children}</Providers>
			</body>
		</html>
	);
}
